# Generated by Django 5.2.8 on 2025-11-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Link externo para imagem (ex: https://exemplo.com/imagem.png)', max_length=500, null=True),
        ),
    ]
